// Fourth card batch: 20 two-sided cards per core category. Blue = well known, yellow = a bit harder.
export const BATCH4: Record<string, { blue: string[]; yellow: string[] }> = {
  general: {
    blue: [
      'Fire Extinguisher', 'Smoke Alarm', 'First Aid Kit', 'Plaster', 'Crutches',
      'Wheelchair', 'Hearing Aid', 'Glasses', 'Toothpaste', 'Dental Floss',
      'Shampoo', 'Soap', 'Towel', 'Bathtub', 'Shower',
      'Staircase', 'Elevator', 'Escalator', 'Front Door', 'Doorbell',
      'Window', 'Curtains', 'Carpet', 'Couch', 'Bunk Bed',
      'Spoon', 'Fork', 'Knife', 'Frying Pan', 'Oven',
      'Rain Boots', 'Flip Flops', 'Beanie', 'Scarf', 'Gloves',
      'Paint Brush', 'Crayons', 'Glue Stick', 'Colouring Book', 'Sketchpad',
      'Diary', 'Calendar', 'Newspaper', 'Envelope', 'Postage Stamp',
      'Hammer', 'Screwdriver', 'Tape Measure', 'Ladder', 'Toolbox',
      'Treasure Chest', 'Pirate Ship', 'Message in a Bottle', 'Buried Treasure', 'Treasure Map',
      'Cowboy', 'Astronaut Suit', 'Ninja', 'Mermaid', 'Vampire',
      'Robot', 'Martian', 'UFO', 'Flying Saucer', 'Space Station',
      'Volunteer', 'Charity', 'Donation Box', 'Fundraiser', 'Soup Kitchen',
      'Birthday Candles', 'Party Hat', 'Balloon', 'Confetti', 'Pinata',
      'Recipe', 'Shopping List', 'To-Do List', 'Sticky Fingers', 'Leftovers',
      'Seatbelt', 'Airbag', 'Steering Wheel', 'Spare Tyre', 'Petrol Station',
      'Library Card', 'Homework', 'Exam', 'Pencil Case', 'Lunchbox',
      'Wedding Ring', 'Engagement', 'Bouquet', 'Bride', 'Groom',
      'Sunscreen', 'Beach Towel', 'Bucket and Spade', 'Seashell', 'Crab',
    ],
    yellow: [
      'Defibrillator', 'CPR', 'Tourniquet', 'Heimlich Manoeuvre', 'Triage',
      'Prosthetic Limb', 'Braille', 'Guide Dog', 'Orthodontist', 'Root Canal',
      'Loofah', 'Bath Bomb', 'Sauna', 'Jacuzzi', 'Bidet',
      'Spiral Staircase', 'Dumbwaiter', 'Revolving Door', 'Trapdoor', 'Peephole',
      'Stained Glass', 'Venetian Blinds', 'Chaise Longue', 'Ottoman', 'Four-Poster Bed',
      'Ladle', 'Whisk', 'Colander', 'Cast-Iron Pan', 'Mortar and Pestle',
      'Galoshes', 'Espadrilles', 'Balaclava', 'Poncho', 'Mittens',
      'Easel', 'Palette Knife', 'Charcoal Drawing', 'Watercolour', 'Calligraphy',
      'Almanac', 'Encyclopaedia', 'Thesaurus', 'Telegram', 'Wax Seal',
      'Spirit Level', 'Chisel', 'Soldering Iron', 'Vice Grip', 'Allen Key',
      'Doubloon', 'Jolly Roger', 'Walk the Plank', 'Parrot on Shoulder', 'Eye Patch',
      'Samurai', 'Roman Legionary', 'Viking Helmet', 'Centaur', 'Werewolf',
      'Android', 'Hologram', 'Teleporter', 'Time Machine', 'Wormhole',
      'NGO', 'Philanthropist', 'Crowdfunding', 'Telethon', 'Food Bank',
      'Surprise Party', 'Gender Reveal', 'Streamers', 'Party Popper', 'Goodie Bag',
      'Cookbook', 'Meal Prep', 'Grocery Budget', 'Bulk Buying', 'Expiry Date',
      'Cruise Control', 'Handbrake', 'Dashboard Light', 'Jumper Cables', 'Tow Truck',
      'Dewey Decimal', 'Dissertation', 'Invigilator', 'Report Card Comment', 'Detention',
      'Prenup', 'Best Man Speech', 'Garter Toss', 'Vow Renewal', 'Eloping',
      'SPF Rating', 'Rash Vest', 'Tide Pool', 'Sand Dollar', 'Hermit Crab',
    ],
  },
  movies: {
    blue: [
      'Finding Dory', 'Toy Story 3', 'Incredibles 2', 'Cars 2', 'Monsters University',
      'Frozen II', 'Moana 2', 'Inside Out 2', 'Despicable Me 4', 'Kung Fu Panda 4',
      'The Lion King 2019', 'Aladdin 2019', 'Maleficent Movie', 'Cruella', 'Mary Poppins Returns',
      'Iron Man 2', 'Thor: Ragnarok', 'Guardians of the Galaxy', 'Captain Marvel', 'Shang-Chi',
      'The Batman', 'Man of Steel', 'Justice League', 'Suicide Squad', 'Shazam!',
      'Jurassic Park Dinosaurs', 'The Lost World', 'Jurassic World Dominion', 'Pacific Rim', 'Kong: Skull Island',
      'The Nun', 'Insidious', 'Paranormal Activity', 'The Ring', 'A Quiet Place',
      'Sonic the Hedgehog Movie', 'The Super Mario Bros. Movie', 'Detective Pikachu', 'Minecraft Movie', 'Uncharted',
      'Harry Potter and the Philosopher\'s Stone', 'Chamber of Secrets', 'Prisoner of Azkaban', 'Goblet of Fire', 'Deathly Hallows',
      'The Fellowship of the Ring', 'The Two Towers', 'Return of the King', 'An Unexpected Journey', 'The Battle of the Five Armies',
      'A New Hope', 'The Empire Strikes Back', 'Return of the Jedi', 'The Force Awakens', 'Rogue One',
      'Home Alone Burglars', 'The Santa Clause', 'Polar Express', 'Jingle All the Way', 'Arthur Christmas',
      'Mulan 2020', 'The Princess and the Frog', 'Wish', 'Strange World', 'Zootopia Judy Hopps',
      'Bumblebee', 'Real Steel', 'I, Robot', 'Ready Player One', 'Tron',
      'Mission Impossible Fallout', 'Skyfall', 'Casino Royale', 'No Time to Die', 'GoldenEye',
      'Frozen Let It Go', 'Moana How Far I\'ll Go', 'Lion King Hakuna Matata', 'Encanto Bruno', 'Tangled Lanterns',
      'Night at the Museum 2', 'Jumanji: Welcome to the Jungle', 'Journey to the Center of the Earth', 'Zathura', 'Holes',
      'Ghost', 'Dirty Harry', 'Die Hard with a Vengeance', 'Lethal Weapon', 'Beverly Hills Cop',
      'The Hangover', 'Superbad', 'Step Brothers', 'Anchorman', 'Zoolander',
      'Selma', 'Hidden Figures', '12 Years a Slave', 'The Help', 'Ray',
    ],
    yellow: [
      'Luxo Jr.', 'A Bug\'s Life', 'Lightyear', 'Onward Elves', 'Brave Merida',
      'Frozen Fever', 'Moana Maui Hook', 'Inside Out Bing Bong', 'Gru\'s Lab', 'Tai Lung',
      'Lion King Stampede', 'Genie Blue', 'Diablo the Raven', 'Horace and Jasper', 'Admiral Boom',
      'Stark Expo', 'Hela', 'Groot', 'Goose the Flerken', 'Ten Rings',
      'The Riddler', 'General Zod', 'Steppenwolf', 'Harley Quinn', 'Black Adam',
      'Dilophosaurus', 'Mosasaurus', 'Indominus Rex', 'Jaeger', 'Skullcrawler',
      'Valak', 'The Further', 'Poltergeist Clown', 'Samara', 'Evelyn Abbott',
      'Knuckles', 'Bowser', 'Mewtwo', 'Steve (Minecraft)', 'Nathan Drake',
      'Platform Nine and Three-Quarters', 'Basilisk', 'Dementor', 'Triwizard Cup', 'Elder Wand',
      'The One Ring', 'Helm\'s Deep', 'Mount Doom', 'Smaug', 'Thorin Oakenshield',
      'Death Star', 'Hoth', 'Ewoks', 'Rey', 'Jyn Erso',
      'Wet Bandits', 'Elf Bernard', 'Hero Boy', 'Turbo-Man', 'Grand-Santa',
      'Mushu', 'Ray the Firefly', 'Asha', 'Splat', 'Flash the Sloth',
      'Optimus Prime', 'Atom the Robot', 'Sonny', 'Wade Watts', 'Light Cycle',
      'Ethan Hunt', 'Silva', 'Le Chiffre', 'Safin', 'Alec Trevelyan',
      'Ice Palace', 'Te Fiti', 'Pride Rock', 'Casita', 'Floating Lanterns',
      'Ahkmenrah', 'Jumanji Jaguar Shrine', 'Icelandic Volcano Tube', 'Zathura Robot', 'Camp Green Lake',
      'Pottery Wheel Scene', 'Harry Callahan', 'Zeus Carver', 'Riggs and Murtaugh', 'Axel Foley',
      'Wolfpack', 'McLovin', 'Catalina Wine Mixer', 'Ron Burgundy', 'Blue Steel',
      'Edmund Pettus Bridge', 'Katherine Johnson', 'Solomon Northup', 'Minny Jackson', 'Ray Charles',
    ],
  },
  sports: {
    blue: [
      'Soccer Mom', 'Sunday League', 'Five-a-Side', 'Street Soccer', 'Keepy-Uppy',
      'Crossbar', 'Penalty Spot', 'Centre Circle', 'Touchline', 'Kick-Off',
      'Slam Dunk Contest', 'All-Star Game', 'Jersey Retirement', 'Playoffs', 'Finals MVP',
      'Chris Gayle', 'MS Dhoni', 'Rohit Sharma', 'Ben Stokes', 'Joe Root',
      'Lionel Messi World Cup', 'Cristiano Ronaldo Siuu', 'Neymar Skill', 'Mbappe Speed', 'Haaland Goal',
      'Beach Soccer', 'Futsal', 'Indoor Cricket', 'Touch Rugby', 'Tag Rugby',
      'Jump Rope', 'Hula Hoop', 'Frisbee', 'Roller Skates', 'Scooter',
      'Speedboat Racing', 'Rowing Boat', 'Canoe', 'Raft', 'Sailboat',
      'Horse Riding', 'Pony', 'Saddle', 'Horseshoe', 'Stable',
      'Weightlifter', 'Bodybuilder', 'Strongman', 'Sumo Wrestler', 'Gymnast',
      'Balance Beam', 'Pommel Horse', 'Uneven Bars', 'Floor Routine', 'Vault',
      'Ice Hockey Goalie', 'Curling Stone', 'Bobsleigh Team', 'Ski Jumper', 'Snowboarder',
      'Racing Car', 'Motorbike', 'Helmet', 'Race Track', 'Pole Position',
      'Stadium Seats', 'Ticket Booth', 'Hot Dog Stand', 'Jumbotron', 'Kiss Cam',
      'Team Bus', 'Training Camp', 'Tryouts', 'Bench Warmer', 'Rookie',
      'World Record', 'Silver Medal', 'Bronze Medal', 'Participation Trophy', 'Hall of Fame',
      'Dodgeball', 'Kickball', 'Rounders', 'Netball Hoop', 'Softball',
      'Marathon Runner', 'Water Station', 'Energy Bar', 'Medal Bite', 'Victory Lap',
      'Personal Record', 'Stretching', 'Jogging', 'Morning Run', 'Park Run',
      'Coach Whistle', 'Tactics Board', 'Team Talk', 'Huddle', 'High Five',
    ],
    yellow: [
      'Tifosi', 'Non-League', 'Rondo Drill', 'Panna Knockout', 'Rainbow Flick',
      'Woodwork', 'D-Box Arc', 'Technical Area', 'Fourth Official', 'Drop Ball',
      'Dunk Contest Free-Throw Line', 'Load Management', 'Buyout Clause', 'Play-In Tournament', 'Larry O\'Brien Trophy',
      'Universe Boss', 'Helicopter Shot', 'Hitman', 'Headingley Miracle', 'Bazball',
      'Hand of God', 'Siuu Celebration', 'Neymar Roll', 'Turtle Celebration', 'Cyborg Striker',
      'Bicycle Kick Beach', 'Futsal Pivot', 'Indoor Nets', 'Six-Second Touch', 'Tag Belt',
      'Double Dutch', 'Diabolo', 'Ultimate Frisbee', 'Roller Derby', 'Freestyle Scooter',
      'Hydroplane', 'Sculling', 'Dragon Boat', 'White-Water Rafting', 'Regatta',
      'Gymkhana', 'Farrier', 'Martingale', 'Canter', 'Dressage Test',
      'Clean and Jerk', 'Snatch Lift', 'Atlas Stones', 'Yokozuna', 'Tsukahara Vault',
      'Aerial Walkover', 'Flair Spin', 'Giant Swing', 'Tumbling Pass', 'Yurchenko',
      'Butterfly Save', 'Hammer Stone', 'Brakeman', 'Telemark Landing', 'Rail Grind',
      'Downforce', 'Slipstream', 'Chicane', 'Hairpin Bend', 'Parc Ferme',
      'Luxury Box', 'Turnstile', 'Concession Stand', 'Seventh-Inning Stretch', 'Kiss and Cry Area',
      'Away Kit', 'Preseason Tour', 'Combine Drills', 'Utility Player', 'Journeyman',
      'Olympic Record', 'Podium Finish', 'Wooden Spoon', 'Lifetime Ban', 'Induction Ceremony',
      'Gaga Ball', 'Four Square', 'Pickleball', 'Padel', 'Teqball',
      'Negative Split Pace', 'Hitting the Wall', 'Gel Pack', 'Split Time', 'Negative Mile',
      'Parkrun Tourism', 'Dynamic Stretching', 'Tempo Run', 'Fartlek', 'Strides',
      'Set Piece', 'Low Block', 'High Press', 'Counter-Attack', 'Man-Marking',
    ],
  },
  geography: {
    blue: [
      'Alps Ski Resort', 'Swiss Chocolate', 'Belgian Waffles', 'Italian Pizza', 'Spanish Flamenco',
      'Egypt Camel', 'Kenya Maasai', 'Ethiopia Coffee', 'Madagascar Lemur', 'Morocco Tagine',
      'Brazil Football', 'Argentina Steak', 'Mexico Sombrero', 'Peru Machu Picchu Trail', 'Chile Wine',
      'Japan Sushi', 'Korea Kimchi', 'China Great Wall Hike', 'India Curry', 'Thailand Tuk-Tuk',
      'Canada Maple Syrup', 'USA Burger', 'Hawaii Surfing', 'Alaska Glacier', 'Jamaica Reggae',
      'Russia Winter', 'Iceland Geyser', 'Norway Fjord Cruise', 'Sweden Meatballs', 'Finland Sauna',
      'Australia Outback', 'New Zealand Hobbiton', 'Fiji Island', 'Tahiti', 'Great Barrier Reef Diving',
      'Nile Delta', 'Amazon Rainforest Tribe', 'Congo Rainforest', 'Borneo Jungle', 'Sahara Oasis',
      'Mount Fuji Climb', 'Himalaya Trek', 'Andes Condor', 'Rocky Mountains Bear', 'Alps Cow Bells',
      'Paris Eiffel Tower', 'London Big Ben', 'Rome Colosseum', 'Athens Acropolis', 'Istanbul Mosque',
      'Dubai Skyscraper', 'Singapore Gardens', 'Tokyo Crossing', 'Hong Kong Harbour', 'Sydney Harbour Bridge',
      'New York Statue', 'Rio Christ Statue', 'Cairo Pyramids', 'Moscow Red Square', 'Beijing Forbidden City',
      'Capital City Quiz', 'Country Flag Quiz', 'World Cup Host', 'Olympic Host City', 'Continent Count',
      'Equator Line', 'North Pole Santa', 'South Pole Station', 'Arctic Fox', 'Polar Bear',
      'Desert Camel', 'Jungle Monkey', 'Ocean Whale', 'River Hippo', 'Mountain Goat',
      'Longest River', 'Highest Mountain', 'Biggest Desert', 'Largest Ocean', 'Smallest Country',
      'Island Nation', 'Landlocked', 'Coastline', 'Peninsula Country', 'Border Crossing',
      'Time Difference', 'Jet Plane', 'Cruise Ship', 'Road Trip Map', 'Train Journey',
      'Hot Country', 'Cold Country', 'Rainy Season', 'Dry Season', 'Four Seasons',
      'World Heritage Site', 'National Park', 'Nature Reserve', 'Botanical Garden', 'Zoo',
    ],
    yellow: [
      'Zermatt', 'Bruges', 'Naples', 'Seville', 'Granada Alhambra',
      'Luxor', 'Maasai Mara', 'Lalibela', 'Avenue of the Baobabs', 'Marrakech Medina',
      'Maracana', 'Patagonia Glacier', 'Teotihuacan', 'Rainbow Mountain', 'Atacama Stargazing',
      'Tsukiji Market', 'DMZ', 'Terracotta Army', 'Kerala Backwaters', 'Phi Phi Islands',
      'Banff', 'Grand Teton', 'Na Pali Coast', 'Denali National Park', 'Blue Mountains Jamaica',
      'Trans-Siberian Railway', 'Blue Lagoon', 'Lofoten Islands', 'Icehotel', 'Lapland',
      'Kakadu', 'Milford Sound', 'Bora Bora', 'Moorea', 'Ningaloo Reef',
      'Nile Cataracts', 'Yanomami', 'Okapi Habitat', 'Orangutan Sanctuary', 'Siwa Salt Lakes',
      'Aokigahara', 'Annapurna Circuit', 'Colca Canyon', 'Glacier National Park', 'Jungfraujoch',
      'Sacre-Coeur', 'Westminster Abbey', 'Pantheon Rome', 'Delphi', 'Hagia Sophia',
      'Palm Jumeirah', 'Marina Bay Sands', 'Shibuya Scramble', 'Victoria Peak', 'Bondi Beach',
      'Ellis Island', 'Sugarloaf Mountain', 'Giza Plateau', 'St Basil\'s Cathedral', 'Tiananmen Square',
      'Naypyidaw', 'Canberra', 'Ottawa', 'Brasilia', 'Wellington',
      'Kiribati Date Line', 'Magnetic North', 'McMurdo Station', 'Svalbard Seed Vault', 'Walrus',
      'Dromedary', 'Howler Monkey', 'Narwhal', 'Pygmy Hippo', 'Ibex',
      'Amazon Discharge', 'Challenger Deep', 'Dead Sea Shoreline', 'Angel Falls', 'Nauru Size',
      'Archipelago Nation', 'Double Landlocked', 'Fjord Coastline', 'Iberian Peninsula', 'Schengen Area',
      'International Date Line Jump', 'Great Circle Route', 'Panama Transit', 'Rail Gauge', 'Orient Express',
      'Continental Climate', 'Maritime Climate', 'Wet Season', 'Harmattan Season', 'Midnight Sun Summer',
      'UNESCO Listing', 'Biosphere Reserve', 'Marine Protected Area', 'Kew Gardens', 'Safari Park',
    ],
  },
  entertainment: {
    blue: [
      'Taylor Swift Shake It Off', 'Adele Hello', 'Bruno Mars Uptown Funk', 'Pharrell Happy', 'Ed Sheeran Shape of You',
      'Beyonce Single Ladies', 'Rihanna Diamonds', 'Michael Jackson Thriller', 'Queen We Will Rock You', 'ABBA Dancing Queen',
      'Whitney Houston', 'Mariah Carey Christmas', 'Celine Dion Titanic Song', 'Elton John', 'Stevie Wonder',
      'Bob Marley', 'Tupac', 'Biggie', 'Snoop Dogg', 'Missy Elliott',
      'The Voice', 'America\'s Got Talent', 'Britain\'s Got Talent', 'X Factor', 'American Idol',
      'Dancing with the Stars', 'Lip Sync Battle', 'Wheel of Fortune', 'Who Wants to Be a Millionaire', 'Deal or No Deal',
      'Netflix Kdrama', 'Anime Series', 'Naruto', 'Dragon Ball', 'One Piece',
      'Peppa Pig', 'Bluey', 'Paw Patrol', 'Dora the Explorer', 'Teletubbies',
      'Sesame Street', 'Barney', 'Thomas the Tank Engine', 'Bob the Builder', 'Postman Pat',
      'Uno', 'Snakes and Ladders', 'Ludo', 'Jenga', 'Connect Four',
      'Hide and Seek', 'Tag Game', 'Simon Says', 'Duck Duck Goose', 'Red Light Green Light',
      'Theme Park Ride', 'Ferris Wheel', 'Bumper Cars', 'Haunted House', 'Candy Floss',
      'Stage Lights', 'Fog Machine', 'Confetti Cannon', 'Glow Sticks', 'VIP Section',
      'Autograph Signing', 'Meet and Greet', 'Fan Mail', 'Fan Art Wall', 'Selfie with a Celeb',
      'TikTok Dance', 'Instagram Reel', 'YouTube Vlog', 'Snapchat Filter', 'Facebook Live',
      'Nintendo 64', 'Game Boy', 'PlayStation 5', 'Xbox Controller', 'VR Headset',
      'Call of Duty Warzone', 'FIFA Ultimate Team', 'GTA Online', 'Fall Guys', 'Clash of Clans',
      'Superhero Movie Marathon', 'Movie Sequel Hype', 'Spoiler Alert', 'Post-Credits Hype', 'Opening Weekend',
      'Harry Potter Wand', 'Hogwarts House', 'Sorting Hat', 'Quidditch', 'Golden Snitch',
      'Stand-Up Mic Drop', 'Heckler', 'Punchline', 'Knock-Knock Joke', 'Dad Joke',
    ],
    yellow: [
      'Folklore Album', '21 Album', 'Doo-Wops & Hooligans', 'G I R L', 'Divide Album',
      'Lemonade', 'Anti', 'Bad Album', 'A Night at the Opera', 'Arrival Album',
      'I Will Always Love You', 'Vision of Love', 'My Heart Will Go On', 'Rocket Man', 'Songs in the Key of Life',
      'Exodus Album', 'All Eyez on Me', 'Ready to Die', 'Doggystyle', 'Supa Dupa Fly',
      'Blind Auditions', 'Golden Buzzer', 'Judges\' Houses', 'Bootcamp Round', 'Hometown Visit',
      'Mirrorball Trophy', 'Lip Sync Assassin', 'Vowel Purchase', 'Phone a Friend', 'Banker\'s Offer',
      'Crash Landing on You', 'Attack on Titan', 'Kakashi', 'Super Saiyan', 'Luffy',
      'Daddy Pig', 'Bandit Heeler', 'Chase the Pup', 'Swiper', 'Tubby Custard',
      'Big Bird', 'Baby Bop', 'Fat Controller', 'Scoop the Digger', 'Jess the Cat',
      'Draw Four Card', 'Chutes and Ladders', 'Pachisi', 'Tumbling Tower', 'Four in a Row',
      'Sardines Game', 'British Bulldog', 'Mother May I', 'Grey Duck', 'Squid Game Doll',
      'Log Flume', 'Drop Tower', 'Waltzer', 'Ghost Train', 'Toffee Apple',
      'Pyrotechnics', 'Laser Rig', 'Kabuki Drop', 'LED Wristband', 'Green Room',
      'Signed Vinyl', 'Fan Convention', 'Stan Letter', 'Fan Cam', 'Parasocial Selfie',
      'Choreography Tutorial', 'Duet Remix', 'Unboxing Video', 'AR Lens', 'Watch Party',
      'GoldenEye 007', 'Pokemon Red', 'DualSense', 'Elite Controller', 'Meta Quest',
      'Gulag', 'Pack Opening', 'Heist Mission', 'Crown Win', 'Town Hall Level',
      'Phase Four', 'Shared Universe', 'Spoiler Embargo', 'Mid-Credits Scene', 'Box Office Bomb',
      'Phoenix Feather Core', 'Ravenclaw', 'Hufflepuff', 'Seeker Position', 'Bludger',
      'Crowd Work', 'Tight Five', 'Callback Joke', 'Anti-Joke', 'Pun Battle',
    ],
  },
};
