// Kids & Family deck: words young players can describe and guess. Blue = easy, yellow = a bit trickier.
export const KIDS = {
  blue: [
    'Dog', 'Cat', 'Cow', 'Horse', 'Chicken',
    'Duck', 'Frog', 'Fish', 'Rabbit', 'Monkey',
    'Lion Roar', 'Elephant Trunk', 'Zebra', 'Tiger', 'Bear',
    'Apple', 'Banana', 'Orange', 'Grapes', 'Watermelon',
    'Bread', 'Cheese', 'Milk', 'Juice', 'Sweets',
    'Car', 'Bus Stop', 'Train', 'Boat', 'Rocket',
    'Ball', 'Doll', 'Kite String', 'Blocks', 'Crayon',
    'Sun', 'Moon', 'Star', 'Cloud', 'Rain',
    'Tree', 'Flower', 'Grass', 'Leaf', 'Rock',
    'Shoe', 'Hat', 'Sock', 'Jersey', 'Pyjamas',
    'Teeth', 'Nose', 'Ears', 'Toes', 'Tummy',
    'Bath', 'Bedtime', 'Breakfast', 'Hug', 'Kiss',
    'Birthday', 'Present', 'Party', 'Cake', 'Candle Blow',
    'Mickey Mouse Ears', 'Peppa', 'Elsa\'s Castle', 'Spider Web', 'Dinosaur Egg',
    'Splash Pool', 'Running', 'Jumping', 'Dancing', 'Singing',
    'Class Teacher', 'Nurse', 'Farmer', 'Policeman', 'Builder',
    'Playground', 'Sandpit', 'Swing Set', 'Slide Down', 'Park',
    'Ice Lolly', 'Chips', 'Pizza Slice', 'Pancake', 'Sandwich',
    'Clock', 'Phone', 'TV', 'Lamp', 'Door',
    'Rainbow Colours', 'Bubble', 'Balloon Pop', 'Snowman Nose', 'Puddle Jump',
  ],
  yellow: [
    'Kangaroo', 'Penguin Waddle', 'Owl', 'Squirrel', 'Snail',
    'Bee Sting', 'Butterfly Wings', 'Ladybug', 'Worm', 'Caterpillar',
    'Crocodile Snap', 'Giraffe Neck', 'Hippo Yawn', 'Rhino Horn', 'Cheetah Run',
    'Strawberry', 'Pineapple', 'Mango', 'Coconut', 'Carrot',
    'Broccoli', 'Pumpkin', 'Corn', 'Peas', 'Potato',
    'Helicopter Blades', 'Fire Engine', 'Digger', 'Ambulance Siren', 'Spaceship',
    'Teddy', 'Puzzle', 'Skipping', 'Marble', 'Yo-Yo Trick',
    'Thunder', 'Lightning Flash', 'Wind Blowing', 'Snowflake Catch', 'Fog Walk',
    'Mountain Climb', 'River Splash', 'Beach Sand', 'Forest Walk', 'Cave Echo',
    'Raincoat Hood', 'Slippers', 'Gloves Warm', 'Sunhat', 'Backpack Zip',
    'Elbow', 'Knee', 'Eyebrow', 'Belly Button', 'Chin',
    'Brushing Teeth', 'Washing Hands', 'Tidying Up', 'Bedtime Story', 'Nap Time',
    'Tooth Fairy Coin', 'Christmas Tree', 'Easter Egg Hunt', 'Fireworks', 'Wrapping Paper',
    'Paw Patrol Pup', 'Bluey Dance', 'Minion', 'Shrek Ears', 'Nemo Fish',
    'Hopping', 'Skipping Along', 'Cartwheel', 'Somersault', 'Tiptoe',
    'Dentist', 'Vet', 'Pilot Wings', 'Chef Hat', 'Zookeeper',
    'Treehouse', 'Jungle Gym', 'Merry Go Round', 'Picnic', 'Campfire',
    'Popcorn Pop', 'Jelly Wobble', 'Hot Dog', 'Spaghetti', 'Toast',
    'Alarm Ring', 'Remote', 'Tablet Game', 'Torch', 'Keyhole',
    'Magic Wand', 'Pirate Hat', 'Fairy Wings', 'Superhero Cape', 'Knight Armour',
  ],
};
