// Extra card pool appended to the built-in decks. Blue = well known, yellow = a bit harder.
export const MORE: Record<string, { blue: string[]; yellow: string[] }> = {
  general: {
    blue: [
      'Toothbrush', 'Microwave', 'Umbrella', 'Traffic Light', 'Passport',
      'Smartphone', 'Laptop', 'Headphones', 'Calculator', 'Wristwatch',
      'Heart', 'Brain', 'Rib Cage', 'Lungs', 'Blood Donation',
      'Rainbow', 'Thunderstorm', 'Full Moon', 'Sunset', 'Snowflake',
      'Pizza', 'Chocolate', 'Ice Cream', 'Popcorn', 'Birthday Cake',
      'Hospital', 'Library', 'Post Office', 'Fire Station', 'Supermarket',
      'Doctor', 'Teacher', 'Pilot', 'Firefighter', 'Chef',
      'Piano', 'Guitar', 'Drum Kit', 'Violin', 'Trumpet',
      'Bicycle', 'Aeroplane', 'Helicopter', 'Submarine', 'Hot Air Balloon',
      'Dinosaur', 'Shark', 'Penguin', 'Giraffe', 'Octopus',
      'Queen Elizabeth II', 'Barack Obama', 'Oprah Winfrey', 'Elon Musk', 'Mark Zuckerberg',
      'Google', 'Facebook', 'WhatsApp', 'Instagram', 'Wikipedia',
      'Christmas', 'Easter', 'Halloween', 'Valentine\'s Day', 'New Year\'s Eve',
      'Wedding', 'Graduation', 'Job Interview', 'First Date', 'Road Trip',
      'Coffee', 'Tea Bag', 'Orange Juice', 'Milkshake', 'Bottled Water',
      'Sunglasses', 'High Heels', 'Sneakers', 'Backpack', 'Handbag',
      'Recycling', 'Solar Power', 'Wind Turbine', 'Climate Change', 'Plastic Pollution',
      'Pyramid', 'Castle', 'Lighthouse', 'Skyscraper', 'Bridge',
      'Magnet', 'Microscope', 'Telescope', 'Thermometer', 'X-Ray',
      'Alarm Clock', 'Candle', 'Mirror', 'Pillow', 'Blanket',
      'Bank Card', 'Cash Machine', 'Piggy Bank', 'Shopping Cart', 'Receipt',
      'Superman', 'Santa Claus', 'Tooth Fairy', 'Easter Bunny', 'Cinderella Slipper',
      'Chess', 'Monopoly', 'Scrabble', 'Jigsaw Puzzle', 'Rubik\'s Cube',
      'Leap Year', 'Time Zone Change', 'Daylight', 'Midnight', 'Weekend',
      'Fingerprint', 'Password', 'Selfie', 'Emoji', 'Hashtag',
      'Vitamin C', 'Protein', 'Sugar', 'Salt', 'Caffeine',
      'Bee', 'Butterfly', 'Spider', 'Mosquito', 'Ladybird',
      'Earth', 'Mars', 'Jupiter', 'Saturn', 'The Sun',
      'Ambulance', 'Police Car', 'Taxi', 'School Bus', 'Tractor',
      'Wi-Fi', 'Bluetooth', 'Charger', 'Battery', 'Plug Socket',
    ],
    yellow: [
      'Nikola Tesla', 'Thomas Edison', 'Alexander Graham Bell', 'Wright Brothers', 'Galileo Galilei',
      'Pythagoras', 'Archimedes', 'Aristotle', 'Plato', 'Socrates',
      'Pancreas', 'Appendix', 'Cornea', 'Femur', 'Adrenaline',
      'Stratosphere', 'Ozone Layer', 'Solar Eclipse', 'Meteor Shower', 'Supernova',
      'Sushi', 'Croissant', 'Paella', 'Tiramisu', 'Guacamole',
      'Parliament', 'Senate', 'Supreme Court', 'Embassy', 'Referendum',
      'Architect', 'Archaeologist', 'Astronaut', 'Surgeon', 'Journalist',
      'Saxophone', 'Harp', 'Cello', 'Accordion', 'Xylophone',
      'Concorde', 'Bullet Train', 'Cable Car', 'Hovercraft', 'Space Shuttle',
      'Woolly Mammoth', 'Sabre-Toothed Tiger', 'Dodo', 'Pterodactyl', 'Tyrannosaurus Rex',
      'Winston Churchill', 'Abraham Lincoln', 'Martin Luther King Jr.', 'Napoleon Bonaparte', 'Queen Victoria',
      'Microsoft', 'Amazon', 'Netflix Company', 'Tesla Motors', 'Samsung',
      'Diwali', 'Ramadan', 'Hanukkah', 'Chinese New Year', 'Thanksgiving',
      'Honeymoon', 'Retirement', 'Baby Shower', 'Anniversary', 'Housewarming',
      'Espresso', 'Cappuccino', 'Green Tea', 'Kombucha', 'Smoothie',
      'Bow Tie', 'Top Hat', 'Kimono', 'Sari', 'Kilt',
      'Carbon Footprint', 'Deforestation', 'Greenhouse Gas', 'Biodiversity', 'Composting',
      'Sphinx', 'Acropolis', 'Parthenon', 'Leaning Tower of Pisa', 'Big Ben',
      'Barometer', 'Stethoscope', 'Periscope', 'Seismograph', 'Metronome',
      'Hourglass', 'Sundial', 'Chandelier', 'Hammock', 'Grandfather Clock',
      'Cryptocurrency', 'Bitcoin', 'Stock Market', 'Interest Rate', 'Tax Return',
      'Robin Hood', 'King Arthur', 'Sherlock Holmes', 'Count Dracula', 'Frankenstein',
      'Sudoku', 'Crossword', 'Dominoes', 'Backgammon', 'Mahjong',
      'Equinox', 'Solstice', 'Fortnight', 'Decade', 'Millennium',
      'Two-Factor Authentication', 'Cloud Storage', 'Firewall', 'Algorithm', 'Artificial Intelligence',
      'Vitamin D', 'Calcium', 'Carbohydrate', 'Cholesterol', 'Antioxidant',
      'Praying Mantis', 'Dragonfly', 'Firefly', 'Scorpion', 'Centipede',
      'Mercury Planet', 'Venus', 'Neptune', 'Uranus', 'Pluto',
      'Tuk-Tuk', 'Gondola', 'Rickshaw', 'Segway', 'Monorail',
      'USB Stick', 'Router', 'Hard Drive', 'Motherboard', 'Pixel',
    ],
  },
  movies: {
    blue: [
      'Barbie', 'Oppenheimer', 'Dune', 'Wicked', 'Inside Out',
      'Despicable Me', 'Minions', 'Kung Fu Panda', 'Madagascar Movie', 'Ice Age',
      'Cars', 'Ratatouille', 'Monsters Inc.', 'WALL-E', 'Brave',
      'The Little Mermaid', 'Beauty and the Beast', 'Snow White', 'Sleeping Beauty', 'Tangled',
      'Captain America', 'Thor', 'Hulk', 'Doctor Strange', 'Ant-Man',
      'Wonder Woman', 'Aquaman', 'The Joker', 'Deadpool', 'Venom',
      'Transformers', 'Godzilla', 'King Kong', 'Planet of the Apes', 'The Mummy',
      'Grease', 'Dirty Dancing', 'Mamma Mia!', 'The Greatest Showman', 'High School Musical',
      'Mean Girls', 'Clueless', 'Legally Blonde', 'The Notebook', 'Pretty Woman',
      'The Lord of the Rings', 'Narnia', 'Fantastic Beasts', 'The Chronicles of Riddick', 'Eragon',
      'Scream', 'The Conjuring', 'IT', 'Annabelle', 'Saw',
      'Rush Hour', 'Bad Boys', 'Men in Black 3', 'Kingsman', 'Sherlock Holmes Movie',
      'The Karate Kid', 'Space Jam', 'Paddington', 'Stuart Little', 'Babe',
      'Jumanji', 'Night at the Museum', 'Honey I Shrunk the Kids', 'Mrs. Doubtfire', 'Matilda',
      'The Sound of Music', 'Mary Poppins', 'Willy Wonka', 'Charlie and the Chocolate Factory', 'Chitty Chitty Bang Bang',
      'Top Gun: Maverick', 'Avatar: The Way of Water', 'Black Panther: Wakanda Forever', 'Spider-Man: No Way Home', 'Avengers: Endgame',
      'Hotel Transylvania', 'The Smurfs', 'Trolls', 'Sing', 'The Secret Life of Pets',
      'Oscar Statue', 'Popcorn Bucket', 'Movie Trailer', 'Box Office', 'Red Carpet Premiere',
      'Director', 'Stunt Double', 'Green Screen', 'Clapperboard', 'Sequel Movie',
      'Tom Cruise', 'Will Smith', 'Leonardo DiCaprio', 'Denzel Washington', 'Dwayne Johnson',
      'Meryl Streep', 'Julia Roberts', 'Angelina Jolie', 'Zendaya', 'Margot Robbie',
      'Morgan Freeman', 'Samuel L. Jackson', 'Keanu Reeves', 'Brad Pitt', 'Johnny Depp',
      'Steven Spielberg', 'James Cameron', 'Christopher Nolan', 'Quentin Tarantino', 'George Lucas',
      'Darth Vader', 'Yoda', 'Luke Skywalker', 'Princess Leia', 'Chewbacca',
      'Gandalf', 'Frodo', 'Gollum', 'Dumbledore', 'Hermione Granger',
      'Jack Sparrow', 'James Bond Car', 'Indiana Jones Hat', 'Terminator Robot', 'RoboCop',
      'Tarzan', 'Pocahontas', 'Hercules', 'The Jungle Book', 'Lilo & Stitch',
      'Encanto Casita', 'Buzz Lightyear', 'Woody', 'Nemo', 'Dory',
      'Simba', 'Mufasa', 'Scar', 'Timon and Pumbaa', 'Rafiki',
      'Elsa', 'Olaf', 'Shrek\'s Donkey', 'Puss in Boots', 'Lord Farquaad',
    ],
    yellow: [
      'Everything Everywhere All at Once', 'Moonlight', 'Nomadland', 'The Shape of Water', 'Birdman',
      'Spirited Away', 'My Neighbour Totoro', 'Princess Mononoke', 'Howl\'s Moving Castle', 'Akira',
      'Tsotsi', 'District 9', 'Chappie', 'Inxeba', 'Skin (2008)',
      'Lawrence of Arabia', 'Ben-Hur', 'Doctor Zhivago', 'The Bridge on the River Kwai', 'Spartacus Film',
      'Get Out', 'Us', 'Nope', 'Hereditary', 'Midsommar',
      'Knives Out', 'Glass Onion', 'Gone Girl', 'Se7en', 'Zodiac',
      'The Grand Budapest Hotel', 'Moonrise Kingdom', 'Fantastic Mr. Fox', 'Isle of Dogs', 'Asteroid City',
      'Arrival', 'Sicario', 'Prisoners', 'Blade Runner 2049', 'Enemy',
      'Her', 'Lost in Translation', 'Eternal Sunshine of the Spotless Mind', 'Being John Malkovich', 'Adaptation',
      'Drive', 'Nightcrawler', 'Uncut Gems', 'Good Time', 'The Lighthouse',
      'Schindler\'s List', 'Saving Private Ryan', 'Dunkirk', '1917', 'Hacksaw Ridge',
      'Titanic Iceberg Scene', 'The Truman Show', 'Groundhog Day', 'The Big Lebowski', 'Fargo',
      'Rain Man', 'One Flew Over the Cuckoo\'s Nest', 'Taxi Driver', 'The Deer Hunter', 'Platoon',
      'Casablanca Ending', 'Singin\' in the Rain', 'Some Like It Hot', 'Roman Holiday', 'Breakfast at Tiffany\'s',
      'Heat', 'Collateral', 'The Irishman', 'Killers of the Flower Moon', 'Gangs of New York',
      'Toy Story 4', 'Soul', 'Luca', 'Turning Red', 'Elemental',
      'Wallace and Gromit', 'Chicken Run', 'Coraline', 'Kubo and the Two Strings', 'Paranorman',
      'Cinematographer', 'Screenplay', 'Film Score', 'Montage', 'Cameo Appearance',
      'Cate Blanchett', 'Viola Davis', 'Tilda Swinton', 'Frances McDormand', 'Charlize Theron',
      'Daniel Day-Lewis', 'Joaquin Phoenix', 'Anthony Hopkins', 'Gary Oldman', 'Cillian Murphy',
      'Martin Scorsese', 'Stanley Kubrick', 'Alfred Hitchcock', 'Greta Gerwig', 'Denis Villeneuve',
      'Hans Zimmer', 'John Williams', 'Ennio Morricone', 'Danny Elfman', 'Howard Shore',
      'Hannibal Lecter', 'Norman Bates', 'Travis Bickle', 'Tyler Durden', 'Keyser Soze',
      'Obi-Wan Kenobi', 'Boba Fett', 'Kylo Ren', 'Palpatine', 'Mandalorian',
      'Aragorn', 'Legolas', 'Sauron', 'Bilbo Baggins', 'Saruman',
      'Severus Snape', 'Voldemort', 'Hagrid', 'Dobby', 'Bellatrix Lestrange',
      'Maleficent', 'Ursula', 'Jafar', 'Cruella de Vil', 'Gaston',
      'Miguel (Coco)', 'Carl Fredricksen', 'Mr. Incredible', 'Edna Mode', 'Remy the Rat',
      'Katniss Everdeen', 'Bella Swan', 'Edward Cullen', 'Neo', 'Morpheus',
      'Ellen Ripley', 'Sarah Connor', 'John McClane', 'Rocky Balboa', 'Forrest Gump Bench',
    ],
  },
  sports: {
    blue: [
      'Kylian Mbappe', 'Erling Haaland', 'Neymar', 'Mohamed Salah', 'Kevin De Bruyne',
      'Manchester United', 'Liverpool FC', 'Real Madrid', 'Barcelona FC', 'Chelsea FC',
      'Arsenal', 'Manchester City', 'Bayern Munich', 'Juventus', 'Paris Saint-Germain',
      'Premier League', 'Champions League', 'AFCON', 'Olympic Torch', 'Gold Medal',
      'Goal', 'Penalty Shootout', 'Offside', 'Own Goal', 'VAR',
      'Stephen Curry', 'Kobe Bryant', 'Shaquille O\'Neal', 'NBA', 'Three-Pointer',
      'Lewis Hamilton', 'Max Verstappen', 'Pit Stop', 'Chequered Flag', 'Grand Prix',
      'Mike Tyson', 'Floyd Mayweather', 'Knockout', 'Boxing Gloves', 'Heavyweight Belt',
      'Tennis Racket', 'Deuce', 'Ace Serve', 'Tie-Break', 'Ball Boy',
      'Bowling Alley', 'Strike', 'Spare', 'Gutter Ball', 'Bowling Pin',
      'Cricket Bat', 'Wicket', 'Six', 'Run Out', 'LBW',
      'Rugby Ball', 'Try', 'Lineout', 'Conversion Kick', 'Tackle',
      'Swimming Pool', 'Butterfly Stroke', 'Backstroke', 'Freestyle', 'Diving Board',
      'Skateboard', 'Kickflip', 'Half-Pipe', 'Tony Hawk', 'Skate Park',
      'Treadmill', 'Dumbbell', 'Push-Up', 'Sit-Up', 'Personal Trainer',
      'Yoga', 'Pilates', 'Zumba', 'Spinning Class', 'CrossFit',
      'Horse Racing', 'Jockey', 'Rodeo', 'Show Jumping', 'Polo Horse',
      'Hockey Stick', 'Puck', 'Ice Rink', 'Figure Skating', 'Zamboni',
      'Golf Club', 'Hole in One', 'Caddie', 'Putting Green', 'Birdie',
      'Relay Race', 'Hurdles', 'Sprint', 'Javelin', 'Discus',
      'Referee Whistle', 'Half Time', 'Injury Time', 'Hat-Trick Hero', 'Captain\'s Armband',
      'Fan Zone', 'Mexican Wave', 'Vuvuzela', 'Season Ticket', 'Jersey Swap',
      'Esports', 'FIFA Video Game', 'Fantasy Football', 'Sports Betting', 'Transfer Window',
      'Tug of War', 'Sack Race', 'Egg and Spoon Race', 'Three-Legged Race', 'Musical Chairs',
      'Paddleboarding', 'Kayaking', 'Scuba Diving', 'Kitesurfing', 'Jet Ski',
      'Paintball', 'Laser Tag', 'Go-Karting', 'Trampoline Park', 'Mini Golf',
      'Arm Wrestling', 'Kickboxing', 'MMA', 'UFC', 'Taekwondo',
      'Pele', 'Diego Maradona', 'Zinedine Zidane', 'David Beckham', 'Ronaldinho',
      'Stadium Floodlights', 'Scoreboard Clock', 'Dugout', 'Locker Room', 'Trophy Parade',
      'Sports Drink', 'Protein Shake', 'Energy Gel', 'Ice Bath', 'Warm-Up',
    ],
    yellow: [
      'Jude Bellingham', 'Vinicius Junior', 'Bukayo Saka', 'Pedri', 'Lamine Yamal',
      'Ballon d\'Or', 'Golden Boot', 'Treble', 'Relegation', 'Promotion Playoff',
      'Tiki-Taka', 'Gegenpressing', 'False Nine', 'Catenaccio', 'Total Football',
      'Giannis Antetokounmpo', 'Nikola Jokic', 'Victor Wembanyama', 'Luka Doncic', 'Kevin Durant',
      'Ayrton Senna', 'Michael Schumacher', 'Niki Lauda', 'DRS', 'Safety Car',
      'Manny Pacquiao', 'Canelo Alvarez', 'Oleksandr Usyk', 'Tyson Fury', 'Anthony Joshua',
      'Roland Garros', 'US Open Tennis', 'Australian Open', 'Carlos Alcaraz', 'Jannik Sinner',
      'Coco Gauff', 'Iga Swiatek', 'Aryna Sabalenka', 'Naomi Osaka', 'Venus Williams',
      'Duckworth-Lewis', 'Googly', 'Yorker', 'Maiden Over', 'Silly Point',
      'Sachin Tendulkar', 'Virat Kohli', 'Shane Warne', 'Brian Lara', 'Jacques Kallis',
      'Maul', 'Ruck', 'Sin Bin', 'Drop Goal', 'Grubber Kick',
      'Jonah Lomu', 'Richie McCaw', 'Dan Carter', 'Antoine Dupont', 'Joost van der Westhuizen',
      'Individual Medley', 'Tumble Turn', 'Anchor Leg', 'Photo Finish Camera', 'Personal Best',
      'Ollie', 'Grind Rail', 'Vert Ramp', 'Nosegrab', 'Frontside',
      'Deadlift', 'Bench Press', 'Kettlebell', 'Burpee', 'Plank Hold',
      'Downward Dog', 'Sun Salutation', 'Vinyasa', 'Barre Class', 'Tai Chi',
      'Grand National', 'Kentucky Derby', 'Melbourne Cup', 'Dressage', 'Eventing',
      'Wayne Gretzky', 'Power Play Goal', 'Faceoff', 'Axel Jump', 'Triple Salchow',
      'Masters Tournament', 'Green Jacket', 'Eagle', 'Albatross', 'Bogey',
      'Heptathlon', 'Hammer Throw', 'Triple Jump', 'Pace Setter', 'Starting Blocks',
      'Stoppage Time', 'Aggregate Score', 'Away Goals Rule', 'Golden Goal', 'Silver Goal',
      'Ultras', 'Tifo Display', 'Derby Day', 'El Clasico', 'Soweto Derby',
      'League of Legends', 'Counter-Strike', 'Dota 2', 'Twitch Streamer', 'Speedrun',
      'Octathlon', 'Ironman Triathlon', 'Ultramarathon', 'Parkour', 'Obstacle Course Race',
      'Canyoning', 'Abseiling', 'Bouldering', 'Free Solo', 'Base Jumping',
      'Sepak Takraw Kick', 'Hurling', 'Gaelic Football', 'Aussie Rules', 'Shinty',
      'Brazilian Jiu-Jitsu', 'Muay Thai', 'Sambo', 'Krav Maga', 'Aikido',
      'Johan Cruyff', 'Franz Beckenbauer', 'Eusebio', 'George Weah', 'Samuel Eto\'o',
      'Anfield', 'Camp Nou', 'Santiago Bernabeu', 'Old Trafford', 'San Siro',
      'Lactic Acid', 'Carb Loading', 'Altitude Training', 'Hydration Pack', 'Cool-Down',
    ],
  },
  geography: {
    blue: [
      'Kenya', 'Nigeria', 'Ghana', 'Zimbabwe', 'Botswana',
      'Namibia', 'Mozambique', 'Lesotho', 'Eswatini', 'Zambia',
      'Morocco', 'Ethiopia', 'Tanzania', 'Uganda', 'Rwanda',
      'United States', 'United Kingdom', 'Ireland', 'Portugal', 'Greece',
      'Turkey', 'Saudi Arabia', 'Dubai', 'Israel', 'Iran',
      'Thailand', 'Vietnam', 'Indonesia', 'Philippines', 'South Korea',
      'Pakistan', 'Bangladesh', 'Sri Lanka', 'Nepal', 'Singapore',
      'Chile', 'Peru', 'Colombia', 'Cuba', 'Jamaica',
      'Hollywood Sign', 'Golden Gate Bridge', 'Times Square', 'Las Vegas', 'Disney World',
      'Venice', 'Rome', 'Barcelona', 'Amsterdam', 'Berlin',
      'Bali', 'Maldives', 'Mauritius', 'Seychelles', 'Zanzibar',
      'Mount Kenya', 'Table Bay', 'Lake Malawi', 'Zambezi River', 'Orange River',
      'Map', 'Globe', 'Compass Needle', 'Hemisphere', 'Tropics',
      'Beach', 'Cliff', 'Waterfall', 'Cave', 'Forest',
      'Lake', 'River Mouth', 'Bay', 'Harbour', 'Canal',
      'Mountain Range', 'Valley', 'Hill', 'Swamp', 'Savannah',
      'City Centre', 'Suburb', 'Village', 'Farm', 'Highway',
      'Airport', 'Train Station', 'Bus Terminal', 'Port', 'Border Post',
      'Capital', 'Country', 'Province', 'Continent Africa', 'Asia',
      'Europe', 'North America', 'South America', 'Oceania', 'Middle East',
      'Snow', 'Sandstorm', 'Hurricane', 'Tornado', 'Flood',
      'Heatwave', 'Drought', 'Fog', 'Hail', 'Lightning',
      'Eiffel Tower View', 'Burj Khalifa', 'Sydney Opera House', 'Christ the Redeemer', 'Colosseum Rome',
      'Stonehenge Circle', 'Buckingham Palace', 'Tower Bridge', 'Big Ben Clock', 'London Eye',
      'Hong Kong', 'Shanghai', 'Beijing', 'Seoul', 'Bangkok',
      'Lagos', 'Accra', 'Addis Ababa', 'Kigali', 'Harare',
      'Windhoek', 'Gaborone', 'Maputo', 'Maseru', 'Lusaka',
      'Toronto', 'Los Angeles', 'Miami', 'Chicago', 'Mexico City',
      'Buenos Aires', 'Lima', 'Havana', 'Kingston', 'Bogota',
      'Mount Everest Base Camp', 'Kilimanjaro Summit', 'Sahara Camel Ride', 'Nile Cruise', 'Amazon Jungle',
    ],
    yellow: [
      'Djibouti', 'Eritrea', 'Burkina Faso', 'Cabo Verde', 'Comoros',
      'Sao Tome and Principe', 'Guinea-Bissau', 'Malawi', 'Burundi', 'South Sudan',
      'Mauritania', 'Chad', 'Niger', 'Gabon', 'Benin',
      'Liechtenstein', 'Andorra', 'San Marino', 'Monaco', 'Vatican City',
      'Bhutan', 'Brunei', 'Timor-Leste', 'Maldives Atolls', 'Palau',
      'Uzbekistan', 'Turkmenistan', 'Tajikistan', 'Azerbaijan', 'Armenia',
      'Suriname', 'Guyana', 'Paraguay', 'Uruguay', 'Belize',
      'Tuvalu', 'Nauru', 'Kiribati', 'Tonga', 'Samoa',
      'Mount Aconcagua', 'Mount Elbrus', 'Mount Denali', 'K2', 'Matterhorn',
      'Lake Titicaca', 'Lake Baikal', 'Caspian Sea', 'Aral Sea', 'Lake Tanganyika',
      'Congo River', 'Niger River', 'Mekong River', 'Volga River', 'Rhine River',
      'Great Karoo', 'Namib Desert', 'Danakil Depression', 'Ennedi Plateau', 'Rub al Khali',
      'Strait of Gibraltar', 'Suez Canal', 'Panama Canal', 'Bosphorus', 'Strait of Hormuz',
      'Cape of Good Hope', 'Cape Agulhas', 'Cape Horn', 'Land\'s End', 'North Cape',
      'Mariana Trench', 'Great Rift', 'Mid-Atlantic Ridge', 'Continental Shelf', 'Abyssal Plain',
      'Oasis', 'Wadi', 'Mesa', 'Delta', 'Estuary',
      'Tundra', 'Taiga', 'Pampas', 'Veld', 'Fynbos',
      'Sirocco', 'Mistral', 'Chinook Wind', 'Harmattan', 'Berg Wind',
      'Latitude Zero', 'Tropic of Cancer', 'Arctic Circle', 'Antarctic Circle', 'Greenwich',
      'Megacity', 'Conurbation', 'Urban Sprawl', 'Informal Settlement', 'Gentrification',
      'Enclave', 'Protectorate', 'Territory', 'Commonwealth', 'Federation',
      'Petra Treasury', 'Angkor Temples', 'Chichen Itza', 'Easter Island Statues', 'Great Zimbabwe',
      'Mapungubwe', 'Timgad', 'Lalibela Churches', 'Aksum Obelisk', 'Djenne Mosque',
      'Mount Mulanje', 'Rwenzori Mountains', 'Simien Mountains', 'Atlas Peaks', 'Tibesti Mountains',
      'Skeleton Coast', 'Sossusvlei', 'Fish River Canyon', 'Etosha Pan', 'Makgadikgadi Pans',
      'Victoria Falls Bridge', 'Kariba Dam', 'Cahora Bassa', 'Aswan Dam', 'Three Gorges Dam',
      'Ljubljana Castle', 'Tallinn', 'Riga', 'Vilnius', 'Bratislava',
      'Montevideo', 'Asuncion', 'Quito', 'La Paz', 'Caracas',
      'Ulaanbaatar Steppe', 'Almaty', 'Tbilisi', 'Yerevan', 'Baku',
      'Pitcairn Islands', 'Tristan da Cunha', 'Falkland Islands', 'Faroe Islands', 'Greenland Ice Sheet',
    ],
  },
  entertainment: {
    blue: [
      'Bad Bunny', 'Billie Eilish', 'The Weeknd', 'Bruno Mars', 'Justin Bieber',
      'Lady Gaga', 'Katy Perry', 'Dua Lipa', 'Olivia Rodrigo', 'Harry Styles',
      'Eminem', 'Kanye West', 'Jay-Z', 'Nicki Minaj', 'Cardi B',
      'Burna Boy', 'Wizkid', 'Davido', 'Tems', 'Rema',
      'Friends', 'The Simpsons', 'SpongeBob SquarePants', 'Family Guy', 'The Office',
      'Game of Thrones', 'Stranger Things', 'Squid Game', 'Wednesday', 'Money Heist',
      'Breaking Bad', 'The Crown', 'Bridgerton', 'The Walking Dead', 'Grey\'s Anatomy',
      'Fortnite', 'Minecraft', 'Roblox', 'Candy Crush', 'Among Us',
      'PlayStation', 'Xbox', 'Nintendo Switch', 'Mario', 'Pac-Man',
      'Pokemon', 'Pikachu', 'Sonic the Hedgehog', 'Tetris', 'Angry Birds',
      'Concert', 'Music Festival', 'Mosh Pit', 'Encore', 'Backstage Pass',
      'Microphone', 'Headliner', 'Opening Act', 'DJ Booth', 'Light Show',
      'Karaoke Night', 'Open Mic', 'Talent Show Judge', 'Standing Ovation', 'Curtain Call',
      'Cinema', 'Drive-In', 'Movie Night', 'Binge Night', 'Remote Control',
      'Streaming', 'Playlist', 'Album', 'Music Video', 'Chart Topper',
      'Influencer', 'YouTuber', 'Vlogger', 'Podcaster', 'Streamer',
      'Meme', 'Viral Video', 'Trend', 'Challenge Video', 'Filter',
      'Magazine Cover', 'Paparazzi Photo', 'Gossip', 'Tabloid', 'Scandal',
      'Mickey Mouse', 'Bugs Bunny', 'Scooby-Doo', 'Tom and Jerry', 'Garfield',
      'Barbie Doll', 'LEGO', 'Teddy Bear', 'Hot Wheels', 'Nerf Gun',
      'Batman Symbol', 'Spider-Man Suit', 'Iron Man Suit', 'Captain America Shield', 'Thor\'s Hammer',
      'Cartoon Network', 'Nickelodeon', 'Disney Channel', 'MTV', 'BET Awards',
      'Oscars Night', 'Grammys Night', 'Met Gala', 'Super Bowl Halftime Show', 'Eurovision',
      'Michael Jackson Moonwalk', 'Elvis Hip Shake', 'Beyonce Formation', 'Taylor Swift Eras Tour', 'Rihanna Umbrella',
      'Hip Hop Dance', 'Salsa', 'Ballroom Dancing', 'Line Dance', 'Twerk',
      'Guitar Solo', 'Drum Roll', 'Beatbox', 'Rap Battle', 'Freestyle Rap',
      'Comedy Show', 'Sketch Comedy', 'Impressionist', 'Roast Battle', 'Prank Show',
      'Book Club', 'Audiobook', 'Bestseller', 'Kindle', 'Bookshop',
      'Harry Potter Books', 'The Hunger Games Books', 'Diary of a Wimpy Kid', 'Goosebumps', 'Roald Dahl',
      'Art Gallery', 'Museum', 'Sculpture', 'Graffiti', 'Portrait',
    ],
    yellow: [
      'Kendrick Lamar', 'SZA', 'Doja Cat', 'Travis Scott', 'Post Malone',
      'Frank Ocean', 'Solange', 'Janelle Monae', 'Lauryn Hill', 'Erykah Badu',
      'Fela Kuti', 'Youssou N\'Dour', 'Angelique Kidjo', 'Salif Keita', 'Oumou Sangare',
      'Asake', 'Ayra Starr', 'Tiwa Savage', 'Sarkodie', 'Stonebwoy',
      'Succession', 'The Wire', 'The Sopranos', 'Mad Men', 'Better Call Saul',
      'Severance', 'The Bear', 'Fleabag', 'Atlanta', 'Black Mirror',
      'Chernobyl', 'Band of Brothers', 'True Detective', 'Westworld', 'Shogun',
      'The Legend of Zelda', 'Final Fantasy', 'Grand Theft Auto', 'The Last of Us', 'Elden Ring',
      'Street Fighter', 'Mortal Kombat', 'Halo', 'Call of Duty', 'Red Dead Redemption',
      'Donkey Kong', 'Space Invaders', 'Galaga', 'Frogger', 'Doom',
      'Glastonbury', 'Coachella', 'Burning Man', 'Tomorrowland', 'Woodstock',
      'Stage Diving', 'Crowd Surfing', 'Soundcheck', 'Roadie', 'Setlist',
      'Unplugged Session', 'Tiny Desk Concert', 'Residency Show', 'Farewell Tour', 'Reunion Tour',
      'Film Festival', 'Director\'s Cut', 'Blooper Reel', 'Deleted Scene', 'Easter Egg',
      'Vinyl Record', 'Cassette Tape', 'Walkman', 'Jukebox', 'Gramophone',
      'Content Creator', 'Brand Deal', 'Subscriber Count', 'Algorithm Boost', 'Clickbait',
      'Rickroll', 'Distracted Boyfriend Meme', 'Harlem Shake', 'Gangnam Style', 'Mannequin Challenge',
      'Rolling Stone Magazine', 'Vogue', 'Time Person of the Year', 'Forbes List', 'Billboard Hot 100',
      'Betty Boop', 'Felix the Cat', 'Popeye', 'Woody Woodpecker', 'Pink Panther',
      'Tamagotchi', 'Furby', 'Beyblade', 'Yo-Yo', 'Slinky',
      'Wolverine', 'Black Widow', 'Scarlet Witch', 'Loki', 'Thanos',
      'HBO', 'A24', 'Studio Ghibli', 'Pixar Lamp', 'Marvel Studios',
      'Tony Awards', 'Emmy Awards', 'Golden Globes', 'BAFTA', 'Brit Awards',
      'Prince Purple Rain', 'Madonna Vogue', 'Queen Bohemian Rhapsody', 'Nirvana Nevermind', 'Pink Floyd Prism',
      'Lindy Hop', 'Charleston', 'Moonwalk Dance', 'Robot Dance', 'Floss Dance',
      'Mixtape', 'Remix', 'Sample', 'Featuring Artist', 'Ghostwriter',
      'Dry Humour', 'Satire', 'Parody', 'Slapstick', 'Deadpan',
      'Booker Prize', 'Pulitzer Prize', 'Nobel Prize in Literature', 'Chinua Achebe', 'Chimamanda Ngozi Adichie',
      'Things Fall Apart', 'Nineteen Eighty-Four', 'To Kill a Mockingbird', 'The Great Gatsby', 'Pride and Prejudice',
      'Frida Kahlo', 'Vincent van Gogh', 'Pablo Picasso', 'Banksy', 'Andy Warhol',
    ],
  },
};
